version: "3.7"

services:
  django:
    build: ./
    image: django-ass:latest
    command: "python ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8000:8000"